### ISSUE TITLE
Jest encountered an unexpected token

### ISSUE THREAD

**Issue by lbroudoux** [slemke/keycloak-testcontainer#149]
Hello!

Thanks for this project, looks super promising! I'm trying to use it in https://github.com/microcks/microcks-testcontainers-node to test some Keycloak integration use-case but I'm facing issues importing and using it.

I have done the following things:
* Added `"keycloak-testcontainer": "^0.0.6"`  as a dev dependency in my `package.json`
* Modify [`microcks-container.test.ts`](https://github.com/microcks/microcks-testcontainers-node/blob/main/src/microcks-container.test.ts) to import the needed dep:
```ts
import KeycloakContainer from 'keycloak-testcontainer';
```
* Try starting a container within a test:
```ts
it("should start, load artifacts and contract test mock with OAuth2 context", async () => {
    const network = await new Network().start();

    // Start microcks container and other containers.
    const container = await new MicrocksContainer().withNetwork(network).start();
    const keycloak = await new KeycloakContainer()
        .withNetwork(network)
        .withNetworkAliases("keycloak")
        .withRealmImport(path.resolve(resourcesDir, "myrealm-realm.json"))
        .start();

   // [...]

   // Now stop the containers and the network.
    await container.stop();
    await keycloak.stop();
    await network.stop();
  });
```

but each time I launch a Jest test I've go the following error message:

```sh
 FAIL  src/microcks-container.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/laurent/Development/github/microcks-testcontainers-node/node_modules/keycloak-testcontainer/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { KeycloakContainer } from './container/container.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      19 | import { MicrocksContainer, TestRequest, TestRunnerType, OAuth2GrantType } from "./microcks-container";
      20 |
    > 21 | import KeycloakContainer from 'keycloak-testcontainer';
         | ^
      22 |
      23 | describe("MicrocksContainer", () => {
      24 |   jest.setTimeout(180_000);

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (src/microcks-container.test.ts:21:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.706 s
Ran all test suites matching /\/Users\/laurent\/Development\/github\/microcks-testcontainers-node\/src\/microcks-container.test.ts/i with tests matching "MicrocksContainer should start, load artifacts and contract test mock with OAuth2 context".
```

It looks like Jest complains about using a non-standard module or javascript thing.
I'm quite newbie on Jest and its configuration, I saw that there are many configuration options for Jest (including using stuff like `babel` and such).

Is there a workaround to this issue? Or is it due to my project configuration? 

Thanks for the help!

**Comment by slemke** [comment]
Hey @lbroudoux, thanks for your report! :)

The package is written using [ES module support](https://nodejs.org/api/packages.html#introduction_1). Jest also seems to notice this in the error you posted:

```
SyntaxError: Cannot use import statement outside a module
```

I'll take a deeper look later to see if I can do something about it, but can you try adding `"type": "module"` to your `package.json` in the mean time and see if it works? Depending on your `jest` version this could fix it (or you can try some of the solutions [here](https://stackoverflow.com/questions/35756479/does-jest-support-es6-import-export)). If this does not work, let me know and I'll see what I can improve

**Comment by lbroudoux** [comment]
Hi,

Thanks for above comments. I tried several things from the links you mentioned above but got no luck so far:

**1. Adding `"type": "module"` to my `package.json`**

Produces the same error with jest 29.6.2 or 29.7.0

**2. Adding `"transform": {}` to my `jest.config.js` and execute tests with `node --experimental-vm-modules node_modules/jest/bin/jest.js`**

Produces a slightly different error (with or without `"type": "module"` in `package.json`):

```sh
> @microcks/microcks-testcontainers@0.2.5 test
> node --experimental-vm-modules node_modules/jest/bin/jest.js

 FAIL  src/microcks-container.test.ts
  ● Test suite failed to run

    Must use import to load ES Module: /Users/laurent/Development/github/microcks-testcontainers-node/node_modules/keycloak-testcontainer/dist/index.js

      19 | import { MicrocksContainer, TestRequest, TestRunnerType, OAuth2GrantType } from "./microcks-container";
      20 |
    > 21 | import KeycloakContainer from 'keycloak-testcontainer';
         | ^
      22 |
      23 | describe("MicrocksContainer", () => {

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:850:21)
      at Object.<anonymous> (src/microcks-container.test.ts:21:1)
```

**3. Add my `test` environment to `.babelrc` and `npm install --save-dev @babel/plugin-transform-modules-commonjs`**

Still produces the same error as in the initial message (with or without `"type": "module"` in `package.json`)

```sh
FAIL  src/microcks-container.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/laurent/Development/github/microcks-testcontainers-node/node_modules/keycloak-testcontainer/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { KeycloakContainer } from './container/container.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

I also tried other suggestion using `npm install --save-dev babel-jest` but nothing seems to work.

Did you have some other suggestion?

**Comment by lbroudoux** [comment]
Finally got something working by changing some other stuff!

* Added `"type": "module"` to `package.json`
* Changed my `module` in `tsconfig.json` file from `commonjs` to `es2022`:
```json
{
  "compilerOptions": {
    "incremental": true,
    "target": "es2022",
    "module": "es2022",
    "declaration": true,
    "sourceMap": true,
    "strict": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitOverride": true,
    "composite": true,
    "rootDir": "src",
    "outDir": "build"
  },
  "exclude": [
    "build",
    "jest.config.ts"
  ]
}
```
* Changed my Jest `preset` to `ts-jest/presets/default-esm` and add empty `transform` in `jest.config.ts` file:
```ts
import type { Config } from "jest";

const config: Config = {
  preset: "ts-jest/presets/default-esm",
  resetMocks: true,
  restoreMocks: true,
  transform: {}
};

export default config;
```
* Adapted my `test` command in `package.json`:
```
"test": "cross-env DEBUG=testcontainers* NODE_OPTIONS='--experimental-vm-modules' jest"
```
* Then add global imports that are no longer available by default in proper ESM:
```ts
import { dirname } from 'path';
import { fileURLToPath } from 'url';

import { jest } from '@jest/globals'
```

Checking everything is working at the moment!

**Comment by slemke** [comment]
Great to hear! I used your repository and pretty much did the same steps to make it work. I also had to fix the `__dirname` issue with this:

```js
const __filename = fileURLToPath(import.meta.url);

const __dirname = path.dirname(__filename);
```

I think the biggest issue here is that `commonjs` is not supported and that jest really requires a lot of configuration / support for es modules. Let me mark this as an enhancement and see if I can add support in the next version so you don't have to configure all this stuff.
